[package]
name = "demo-rust-axum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "*"  # Web framework that focuses on ergonomics and modularity.
hyper = { version = "*", features = ["full"] }  # A fast and correct HTTP library.
tokio = { version = "*", features = ["full"] }  # Event-driven, non-blocking I/O platform for writing asynchronous I/O backed applications. 
tower = "*"  # Tower is a library of modular and reusable components for building robust clients and servers.
serde = { version = "*", features = ["derive"] }  # Generic serialization/deserialization framework.
serde_json = "*"  # Serialization/deserialize of JSON data.
tracing = "*"  #  Application-level tracing for Rust.
tracing-subscriber = { version = "*", features = ["env-filter"] }  #  Utilities for implementing and composing `tracing` subscribers. 
