[package]
name = "demo-rust-axum"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.4.8"  # Web framework that focuses on ergonomics and modularity.
hyper = { version = "0.14.17", features = ["full"] }  # A fast and correct HTTP library.
tokio = { version = "1.17.0", features = ["full"] }  # Event-driven, non-blocking I/O platform for writing asynchronous I/O backed applications.
tower = "0.4.12"  # Modular reusable components for building robust clients and servers.
serde = { version = "1.0.136", features = ["derive"] }  # Generic serialization/deserialization framework.
serde_json = "1.0.79"  # Serde serializion/deserialization of JSON data.
tracing = "0.1.32"  #  Application-level tracing for Rust.
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }  #  Utilities for implementing and composing `tracing` subscribers.
once_cell = "1.10.0"  # Single assignment cells and lazy values.
base64 = "0.13" # Encode and decode base64 as bytes or utf8.
http = "0.2.6" # Types for HTTP requests and responses.